[Xorg_compositeproto]
git-tree-sha1 = "1fefd5198de045b3f489224336ae2145e8bd9ea3"

    [[Xorg_compositeproto.download]]
    sha256 = "a03b936447afbf6d4cf5892a538e019d91bd4f1fb659330d0d667eb5ee0e79e7"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_compositeproto_jll.jl/releases/download/Xorg_compositeproto-v0.4.0+1/Xorg_compositeproto.v0.4.0.any.tar.gz"
